spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/taco_cloud
spring.datasource.username=root
spring.datasource.password=,jyb14082010